config/routes.rb
Rails.application.routes.draw do
  resource :profiles do
  end
  
  mount HolidayWorkday::Engine, at: '/holiday_workday'
  resources :linkers do
    put :toggle_status, on: :member
  end
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'linkers#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'successful', to: 'linkers#successful'
  get '*unmatched_route', to: 'application#not_found'

  post 'feishu/card', to: 'feishu#card'
end

app/models/linker.rb
##
# Linker for user's url changed to short path
class Linker < ApplicationRecord
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :url, presence: true, uniqueness: { scope: :email }

  # enum status: %i[sleeping active]

  before_create :set_uid, :set_short_path
  after_create :send_show_url_mail

  def visit
    self.times += 1
    save!
  end

  def toggle_status
    update(status: !status)
  end

  private

  def set_uid
    loop do
      uid = SecureRandom.uuid
      unless Linker.exists?(uid: uid)
        self.uid = uid
        break
      end
    end
  end

  def set_short_path
    loop do
      path = SecureRandom.base64(8).gsub('/', '_').gsub(/=+$/, '')
      unless Linker.exists?(short_path: path)
        self.short_path = path
        break
      end
    end
  end

  def send_show_url_mail
    # SendEmailJob.perform_later(id)
    UserMailer.with(linker: self).generate_short_url.deliver_now
  end
end

app/controllers/linkers_controller.rb
class LinkersController < ApplicationController
  before_action :set_linker, only: %i[edit update destroy toggle_status]
  skip_before_action :authenticate_user!, only: %i[new create edit show successful]

  # GET /linkers
  # GET /linkers.json
  def index
    @linkers = Linker.all
  end

  # GET /linkers/1
  # GET /linkers/1.json
  def show
    @linker = Linker.find_by(uid: params[:id])
  end

  # GET /linkers/new
  def new
    @linker = Linker.new
  end

  # GET /linkers/1/edit
  def edit
    @linker = Linker.find_by(uid: params[:id])
  end

  # POST /linkers
  # POST /linkers.json
  def create
    @linker = Linker.find_by(url: linker_params[:url], email: linker_params[:email])
    @linker ||= Linker.new(linker_params)

    respond_to do |format|
      if @linker.save
        format.html do
          if user_signed_in?
            redirect_to '/'
          else
           redirect_to successful_path, notice: 'Linker was successfully created.'
          end
        end
        format.json { render :show, status: :created, location: @linker }
      else
        format.html { render :new }
        format.json { render json: @linker.errors, status: :unprocessable_entity }
        format.js { render 'validate_form.js.erb' }
      end
    end
  end

  def successful; end

  # PATCH/PUT /linkers/1
  # PATCH/PUT /linkers/1.json
  def update
    respond_to do |format|
      if @linker.update(linker_params)
        format.html { redirect_to @linker, notice: 'Linker was successfully updated.' }
        format.json { render :show, status: :ok, location: @linker }
      else
        format.html { render :edit }
        format.json { render json: @linker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linkers/1
  # DELETE /linkers/1.json
  def destroy
    @linker.destroy
    respond_to do |format|
      format.html { redirect_to linkers_url, notice: 'Linker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  ##
  # PUT /likers/:id/toggle_status
  def toggle_status
    @linker.toggle_status
    render json: { message: 'ok' }
  end

  private

  def set_linker
    @linker = Linker.find_by(id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def linker_params
    p = params.fetch(:linker, {}).permit(:url, :email)
    p[:email] = current_user.email if current_user
    p
  end
end

app/helpers/linkers_helper.rb
module LinkersHelper
  def short_url(linker)
    [request.base_url, linker.short_path].join('/')
  end
end

app/views/linkers/_form.html.erb
<%= form_with(model: linker, local: true) do |form| %>
<div class="group">
  <%= form.label :url, 'Url you want short', class: 'required' %>
  <%= form.text_field :url, class: 'input input-url' %>
  <% if linker.errors.include?(:url) %>
  <small class="text-danger"><%= linker.errors.full_messages_for(:url).join(',') %></small>
  <% end %>
</div>
<div class="group">
  <% if !user_signed_in? %>
  <%= form.label :email, 'email', class: 'required' %>
  <%= form.text_field :email, class: 'input' %>
  <% if linker.errors.include?(:email) %>
  <small class="text-danger"><%= linker.errors.full_messages_for(:email).join(',') %></small>
  <% end %>
  <% end %>
</div>

<div class="actions">
  <%= form.submit 'submit' %>
</div>
<% end %>

app/views/linkers/_table.html.erb
<div>
  <h1 class="title">Manage your short urls</h1>
  <table>
    <thead>
      <tr>
        <th class="col3">url</th>
        <th class="col3">short url</th>
        <th>times</th>
        <th>status</th>
      </tr>
    </thead>
    <tbody>
      <% linkers.each do |linker|%>
      <tr>
        <td><%= link_to linker.url, linker.url %></td>
        <td><%= link_to short_url(linker), short_url(linker) %></td>
        <td><%= linker.times %></td>
        <td>
          <div class="form-check form-switch">
            <input class="form-check-input toggleStatus" type="checkbox" data-id=<%= linker.id %> <%= linker.status ? 'checked' : ''%>>
          </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  const es = document.getElementsByClassName('toggleStatus')
  for (var i = 0, len = es.length | 0; i < len; i = i + 1 | 0) {
    const e = es[i]
    e.onclick = () => {
      fetch(`/linkers/${e.dataset.id}/toggle_status`, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
          },
          credentials: 'same-origin',
        })
        .then(response => response.json())
        .then(data => {
          console.log('Success:', data);
        })
        .catch((error) => {
          console.error('Error:', error);
        });
    }
  }
</script>

app/views/linkers/edit.html.erb
<h1>Editing Linker</h1>
<p><%= @linker.url %></p>
<p><%= short_url(@linker) %></p>
<p><%= @linker.status %></p>

app/views/linkers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Linkers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @linkers.each do |linker| %>
      <tr>
        <td><%= link_to 'Show', linker %></td>
        <td><%= link_to 'Edit', edit_linker_path(linker) %></td>
        <td><%= link_to 'Destroy', linker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linker', new_linker_path %>

app/views/linkers/new.html.erb
<style>
  .half {
    border-right: 1px solid #ddd;
    position: fixed;
    height: 100%;
    width: 40%;
    padding: 0 20px;
  }

  .welcome {
    margin: 30% auto;
    text-align: center;
  }

  table {
    table-layout: fixed;
    width: 100%;
    white-space: nowrap;
  }

  th, td {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    padding: 10px;
  }
  .col3 {
    width: 35%
  }
</style>
<div class="half">
  <% if user_signed_in? %>
  <%= render partial: 'table', locals: {linkers: current_user.linkers} %>
  <% else %>
  <div class="welcome">
    <p>Register account, you will manage short ulrs!</p>
    <%= link_to 'sign login', new_user_session_path %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-sm-12 col-md-5">
  </div>
  <div class="col-sm-12 col-md-7">
    <h1 class="title">Url Shorter</h1>
    <h5>
      Generate short url and send to your email.
    </h5>
    <div id="form">
      <%= render partial: 'linkers/form', locals: {linker: @linker} %>
    </div>
  </div>
</div>

app/views/linkers/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= @linker.url %>
</p>
<p>
  <%= short_url(@linker.short_path) %>
</p>
<p>
  <%= @linker.times %>
</p>
<button>expired</button>

app/views/linkers/successful.html.erb
<h1 class="successful">Short Url has sent to your email, please check it! </h1>

app/views/linkers/validate_form.js.erb
var form = document.querySelector("#form");
form.innerHTML="<%= j( render :partial => 'form', locals: {linker: @linker} ) %>"